customCommands:
  - key: "O"
    command: "git checkout --ours {{ .SelectedFile.Name }}"
    context: "global"
    loadingText: "take ours"

  - key: "T"
    command: "git checkout --theirs {{ .SelectedFile.Name }}"
    context: "global"
    loadingText: "take theirs"

  - key: "C"
    command: "git cherry-pick {{ .SelectedLocalBranch.Name }}"
    context: "localBranches"
    prompts:
    - type: 'confirm'
      title: 'Cherry-pick {{ .SelectedLocalBranch.Name }}?'
      body: 'Are you sure you want to cherry-pick {{ .SelectedLocalBranch.Name }}?'


# Catppuccin Mocha Red
gui:
  theme:
    activeBorderColor:
      - '#f38ba8'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#f38ba8'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'

  authorColors:
    '*': '#b4befe'
