---
- name: Manage system dependencies and dotfiles
  hosts: localhost
  connection: local
  gather_facts: true
  become: false

  tasks:
    - name: Gather facts without sudo
      setup:
      become: false

    - name: Install system packages
      package:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - curl
        - wget
        - python3
        - python3-pip
      when: ansible_os_family != "Darwin"

    - name: Install Homebrew packages (macOS)
      homebrew:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - curl
        - wget
        - python
        - fish
      when: ansible_os_family == "Darwin"

    - name: Install Python packages
      pip:
        name: "{{ item }}"
        state: present
      loop:
        - ansible
        - ansible-core
      become: false

    - name: Install Ansible collections
      ansible.builtin.command: ansible-galaxy collection install -r requirements.yml
      args:
        chdir: "{{ playbook_dir }}"
      become: false

    - name: Create symbolic links for dotfiles
      file:
        src: "{{ playbook_dir }}/../{{ item.src }}"
        dest: "{{ ansible_env.HOME }}/{{ item.dest }}"
        state: link
        force: yes
      loop:
        - { src: "fish/config.fish", dest: ".config/fish/config.fish" }
        - { src: "fish/functions", dest: ".config/fish/functions" }
        - { src: "fish/conf.d", dest: ".config/fish/conf.d" }
        - { src: "git/gitconfig", dest: ".gitconfig" }
        - { src: "git/gitignore", dest: ".gitignore" }
        - { src: "vim/vimrc", dest: ".vimrc" }
        - { src: "tmux/tmux.conf", dest: ".tmux.conf" }
      become: false

    - name: Install Fisher package manager
      shell: "fish -c 'curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source'"
      args:
        creates: "{{ ansible_env.HOME }}/.config/fish/functions/fisher.fish"
      become: false
      when: ansible_os_family != "Windows"

    - name: Install Fisher plugins
      shell: "fish -c 'fisher install {{ item }}'"
      loop:
        - jorgebucaran/fisher
        - jorgebucaran/nvm.fish
        - franciscolourenco/done
      become: false
      when: ansible_os_family != "Windows" 