---
- name: Manage system dependencies and dotfiles
  hosts: localhost
  connection: local
  gather_facts: true
  become: false

  tasks:
    - name: Gather facts without sudo
      setup:
      become: false

    - name: Install system packages
      package:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - curl
        - wget
        - python3
        - python3-pip
      when: ansible_os_family != "Darwin"

    - name: Install Homebrew packages (macOS)
      homebrew:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - curl
        - wget
        - python
        - fish
        - ansible
      when: ansible_os_family == "Darwin"

    - name: Install Python packages (non-macOS)
      pip:
        name: "{{ item }}"
        state: present
      loop:
        - ansible
        - ansible-core
      become: false
      when: ansible_os_family != "Darwin"

    - name: Install Ansible collections
      ansible.builtin.command: ansible-galaxy collection install -r requirements.yml
      args:
        chdir: "{{ playbook_dir }}"
      become: false

    - name: Create backup directory
      file:
        path: "{{ ansible_env.HOME }}/.dotfiles-backup"
        state: directory
        mode: '0755'
      become: false

    - name: Backup existing files and directories
      shell: |
        if [ -e "{{ ansible_env.HOME }}/{{ item.dest }}" ]; then
          mv "{{ ansible_env.HOME }}/{{ item.dest }}" "{{ ansible_env.HOME }}/.dotfiles-backup/{{ item.dest | basename }}_$(date +%Y%m%d_%H%M%S)"
        fi
      loop:
        - { dest: ".zshrc" }
        - { dest: ".zshenv" }
        - { dest: ".p10k.zsh" }
        - { dest: ".profile" }
        - { dest: ".oh-my-bash" }
        - { dest: ".envrc" }
        - { dest: ".aliasrc" }
        - { dest: ".bash_eww" }
        - { dest: ".bash_local" }
        - { dest: ".bashrc" }
        - { dest: ".clang-format" }
        - { dest: ".gitconfig" }
        - { dest: ".gitignore" }
        - { dest: ".vim" }
        - { dest: ".fonts" }
        - { dest: ".config/fish" }
        - { dest: ".config/fontconfig" }
        - { dest: ".config/ghostty" }
        - { dest: ".config/kitty" }
        - { dest: ".config/nix" }
        - { dest: ".config/nvim" }
        - { dest: ".config/sops" }
        - { dest: ".config/tmux" }
        - { dest: ".config/wezterm" }
        - { dest: ".config/wslu" }
        - { dest: ".config/zsh" }
      become: false

    - name: Create symbolic links for dotfiles
      file:
        src: "{{ playbook_dir }}/../{{ item.src }}"
        dest: "{{ ansible_env.HOME }}/{{ item.dest }}"
        state: link
        force: yes
      loop:
        - { src: ".zshrc", dest: ".zshrc" }
        - { src: ".zshenv", dest: ".zshenv" }
        - { src: ".p10k.zsh", dest: ".p10k.zsh" }
        - { src: ".profile", dest: ".profile" }
        - { src: ".oh-my-bash", dest: ".oh-my-bash" }
        - { src: ".envrc", dest: ".envrc" }
        - { src: ".aliasrc", dest: ".aliasrc" }
        - { src: ".bash_eww", dest: ".bash_eww" }
        - { src: ".bash_local", dest: ".bash_local" }
        - { src: ".bashrc", dest: ".bashrc" }
        - { src: ".clang-format", dest: ".clang-format" }
        - { src: ".gitconfig", dest: ".gitconfig" }
        - { src: ".gitignore", dest: ".gitignore" }
        - { src: ".vim", dest: ".vim" }
        - { src: ".fonts", dest: ".fonts" }
        - { src: ".config/fish/config.fish", dest: ".config/fish/config.fish" }
        - { src: ".config/fish/functions", dest: ".config/fish/functions" }
        - { src: ".config/fish/conf.d", dest: ".config/fish/conf.d" }
      become: false

    - name: Install Fisher package manager
      shell: "fish -c 'curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source'"
      args:
        creates: "{{ ansible_env.HOME }}/.config/fish/functions/fisher.fish"
      become: false
      when: ansible_os_family != "Windows"

    - name: Install Fisher plugins
      shell: "fish -c 'fisher install {{ item }}'"
      loop:
        - jorgebucaran/fisher
        - jorgebucaran/nvm.fish
        - franciscolourenco/done
      become: false
      when: ansible_os_family != "Windows" 